apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectName }}-test-{{ .Values.suffix }}
  namespace: {{ .Release.Namespace }}
  labels:
    environment: {{ .Values.projectName }}-test-{{ .Values.suffix }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.projectName }}-test-{{ .Values.suffix }}
  template:
    metadata:
      annotations:
        commit-hash: {{ .Values.commitHash | default "1" | quote }}
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Values.projectName }}-test-{{ .Values.suffix }}
    spec:
      containers:
        - name: {{ .Values.projectName }}-test-{{ .Values.suffix }}
          image: {{ .Values.registry}}/{{ .Values.projectName }}:{{ .Values.imageTag }}
          imagePullPolicy: Always
          env:
            - name: PR_NUMBER
              value: "{{- if ne $.Values.suffix "staging"}}{{ .Values.imageTag }}{{end}}"
            - name: ENV_PROJECT
              value: "{{ .Values.projectName }}"
          {{- range $env := .Values.envs }}
            - name: {{ $env.name }}
              value: {{ $env.value | quote }}
          {{ end }}
          {{ if .Values.volumes }}
          volumeMounts:
          {{ end }}

          {{- range $volume := .Values.volumeMounts }}
            - mountPath: {{ $volume.mountPath }}
              name: data
              subPath: {{ $volume.subPath }}

          {{ end }}

          {{- range $domain := .Values.projects }}

          {{- range $mutation := $domain.mutations }}
            {{ if $mutation.hasExport }}
            - mountPath: {{ $mutation.exportDir }}
              name: data
              subPath: test-{{ $.Values.suffix }}/{{ $mutation.lang }}-export
            {{ end }}
          {{ end }}
          {{ end }}


     
        {{- range $container := .Values.otherContainers }}
           
        - name: {{ $container.name }}
          image: {{ $container.image }}
          ports:
          {{- range $port  := $container.ports }}
            - containerPort: {{ $port.containerPort}}
          {{ end }}
          {{- if $container.envs }}
          env:
          {{- range $env := $container.envs }}
            - name: {{ $env.name }}
              value: {{ $env.value | quote }}
          {{ end }}
          {{ end }}
        {{ end }}
      

      {{ if .Values.volumes }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.projectName }}-nfs-pvc
      {{ end }}
