apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-{{ .Values.imageTag }}
  namespace: {{ .Release.Namespace }}
  labels:
    environment: test-{{ .Values.imageTag }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: test-{{ .Values.imageTag }}
  template:
    metadata:
      annotations:
        commit-hash: {{ .Values.commitHash }}
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: test-{{ .Values.imageTag }}
    spec:
      containers:
        - name: test-{{ .Values.imageTag }}
          image: {{ .Values.registry}}{{ .Values.projectName }}:{{ .Values.imageTag }}
          imagePullPolicy: Always
          {{ if .Values.volumes }}
          volumeMounts:
          {{ end }}

          {{- range $volume := .Values.volumeMounts }}
            - mountPath: {{ $volume.mountPath }}
              name: data
              subPath: {{ $volume.subPath }}

          {{ end }}

          {{- range $domain := .Values.projects }}

          {{- range $mutation := $domain.mutations }}
            {{ if $mutation.hasExport }}
            - mountPath: {{ $mutation.exportDir }}
              name: data
              subPath: test-{{ $.Values.imageTag }}/{{ $mutation.lang }}-export
            {{ end }}
          {{ end }}
          {{ end }}


     
        {{- range $container := .Values.otherContainers }}
           
        - name: {{ $container.name }}
          image: {{ $container.image }}
          ports:
          {{- range $port  := $container.ports }}
            - containerPort: {{ $port.containerPort}}
          {{ end }}
        {{ end }}
      

      {{ if .Values.volumes }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.projectName }}-nfs-pvc
      {{ end }}
