{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.projectName }}-test-{{ .Values.suffix }}
  namespace: {{ .Release.Namespace }}
  labels:
    environment: {{ .Values.projectName }}-test-{{ .Values.suffix }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  {{- range $domain := .Values.projects }}
    - host: "{{- if ne $.Values.suffix "staging"}}test{{ $.Values.suffix }}.{{end}}{{ $domain.name }}.peckadesign.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.projectName }}-test-{{ .Values.suffix }}
                port:
                  number: 80

    {{- range $mutation := $domain.mutations }}

    {{ if ne $mutation.lang "cz"}}

    - host: "{{- if ne $.Values.suffix "staging"}}test{{ $.Values.suffix }}.{{end}}{{ $domain.name }}-{{ $mutation.lang }}.peckadesign.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.projectName }}-test-{{ .Values.suffix }}
                port:
                  number: 80
    {{ end }}
    {{ end }}
  {{ end }}
{{- end }}
