{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    environment: {{ include "fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  {{- range $domain := .Values.projects }}
    - host: "{{- if ne $.Values.imageTag "staging"}}test{{ $.Values.imageTag }}.{{end}}{{ $domain.name }}.peckadesign.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.projectName }}-test-{{ $.Values.imageTag }}
                port:
                  number: {{ $.Values.service.port }}

    {{- range $mutation := $domain.mutations }}

    {{ if ne $mutation.lang "cz"}}

    - host: "{{- if ne $.Values.imageTag "staging"}}test{{ $.Values.imageTag }}.{{end}}{{ $domain.name }}-{{ $mutation.lang }}.peckadesign.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.projectName }}-test-{{ $.Values.imageTag }}
                port:
                  number: {{ $.Values.service.port }}
    {{ end }}
    {{ end }}
  {{ end }}
{{- end }}
