apiVersion: v1
kind: Service
metadata:
  name: test-{{ .Values.imageTag }}
  namespace: {{ .Release.Namespace }}
  labels:
    environment: test-{{ .Values.imageTag }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    app: test-{{ .Values.imageTag }}
  ports:
    - port: 80
