apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    environment: {{ include "fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    app: {{ include "fullname" . }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
  type: {{ .Values.service.type | default "ClusterIP" }}
